---
title: "PSD 03"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output: html_document
---

### Set Working Directory

```{r}
repo  <- gsub  ( "\\\\",  "/",  readClipboard ()  ); repo
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/8. Pengantar Sains Data/03")
```

```{r}
library(stringr)
x <- c('Roti Bangsawan', '081210917432', 'RB@emal.id', 'F3823KSB', 'aku_ketinggalan123@gmail.com')
str_detect(x, 'a')
str_detect(x, '[0-9]')
str_detect(x, '[a-z]')
str_subset(x, '[0-9]')
str_extract(x, '[a-z]')
str_extract_all(x, '[a-z]')
str_extract(x, '[a-z]+')
str_extract_all(x, '[a-z]+')
str_extract_all(x, '[A-Za-z]+')
str_replace(x, 'com|id', 'net')
str_replace_all(x, 'com|id', 'net')
str_replace_all(x, '[^a-z0-9]', '#')
str_remove_all(x, '[._@]+')
```

```{r}
y <- "Rp1.589.000"
y1 <- str_remove_all(y,'[.]'); y1
y1 <- str_extract_all(y1, '[0-9]+'); y1
y1 <- as.numeric(y1); y1
```

```{r}
z <- c('Xiaomi Redmi 9C Smarthpone[4GB/64GB]')

```
