---
title: "PSD 01"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
gsub("\\\\", "/", readClipboard () )
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/7. Pengantar Sains Data/01")
```

### Library

```{r}
library(rvest)
library(tidyverse)
library(rio)
library(kableExtra) 
```

## Contoh Scraping 1 Page

```{r}
universitas = 430
page = 1
url <- paste("https://sinta.kemdikbud.go.id/affiliations/authors/",universitas,"?page=",page,sep="")
sinta <- read_html(url)
html_nodes(sinta, "div.profile-name") %>%  html_text2()
```

```{r}
nama_authors <- html_nodes(sinta, ".profile-name") %>%  html_text2()
nama_dept <- html_nodes(sinta, ".profile-dept") %>%  html_text2()
SINTA_ID <- html_nodes(sinta, "div.profile-id")  %>%  html_text2() %>% gsub("ID : ", "", .)
output <- cbind(SINTA_ID,nama_authors)
output
```

## Contoh Scraping 2 pages

```{r}
universitas = 430 # salah satu universitas
page = 3 #scrapping hingga page ke-?
df_master = data.frame()
for(p in 1:page){
  url <- paste("https://sinta.kemdikbud.go.id/affiliations/authors/",universitas,"?page=",p,sep="")
  sinta <- read_html(url)
  NAMA <- html_nodes(sinta, ".profile-name") %>%  html_text2()
  SINTA_ID <- sinta %>% html_nodes("div.profile-id")  %>%  html_text2() %>% gsub("ID : ", "", .)
  output <- cbind(SINTA_ID,NAMA)
  df_master = rbind(df_master, output)
  print(paste("srapping page", p))
}

```

```{r}
View(df_master)
```

### Export

```{r}
rio::export(df_master, "Master_Authors_430.csv", sep=";")
```

## Contoh Scraping 1 Author

```{r}
i=5973268
url <- paste("https://sinta.kemdikbud.go.id/authors/profile/",i,sep="")
sinta <- read_html(url)
nama_authors <- sinta %>% html_nodes("h3") %>% html_text2()
meta_profile <- sinta %>% html_nodes("div.meta-profile") 
meta_profile <- meta_profile %>% html_nodes("a")
nama_univ <- meta_profile[1] %>% html_text2()
nama_dept <- meta_profile[2] %>% html_text2()
sinta_id <- meta_profile[3] %>% html_text2() %>% gsub("SINTA ID : ", "", .)
stat_profile <- sinta %>% html_nodes("div.pr-num")
SINTA_Score_Overall <- stat_profile[1] %>% html_text2()
SINTA_Score_3Yr <- stat_profile[2] %>% html_text2()
Affil_Score <- stat_profile[3] %>% html_text2()
Affil_Score_3Yr <- stat_profile[4] %>% html_text2()
Table <- sinta %>%
          html_nodes("table") %>% 
          html_table(fill = FALSE) %>% .[[1]]
```

```{r}
data_Scopus <- cbind("Scopus_Artikel"=Table$Scopus[1],"Scopus_Citation"=Table$Scopus[2],"Scopus_HIndex"=Table$Scopus[4])
data_GScholar <- cbind("GScholar_Artikel"=Table$GScholar[1],"GScholar_Citation"=Table$GScholar[2],"GScholar_HIndex"=Table$GScholar[4])
data_WOS <- cbind("WOS_Artikel"=Table$WOS[1],"WOS_Citation"=Table$WOS[2],"WOS_HIndex"=Table$WOS[4])
output = cbind(sinta_id,nama_authors,nama_univ,nama_dept,
           SINTA_Score_Overall,SINTA_Score_3Yr,
           Affil_Score,Affil_Score_3Yr,
           data_Scopus, data_GScholar, data_WOS)
output
```

## Scraping Authors

```{r}
df_master<-read.csv("Master_Authors_430.csv",sep = ";") #akan digunakan sebagai ID untuk scrapping authors detail

SINTA_ID=df_master$SINTA_ID[]
df_authors = data.frame()

for(i in SINTA_ID){
  url <- paste("https://sinta.kemdikbud.go.id/authors/profile/",i,sep="")
  sinta <- read_html(url)
  nama_authors <- sinta %>% html_nodes("h3") %>% html_text2()
  meta_profile <- sinta %>% html_nodes("div.meta-profile") 
  meta_profile <- meta_profile %>% html_nodes("a")
  nama_univ <- meta_profile[1] %>% html_text2()
  nama_dept <- meta_profile[2] %>% html_text2()
  sinta_id <- meta_profile[3] %>% html_text2() %>% gsub("SINTA ID : ", "", .)
  stat_profile <- sinta %>% html_nodes("div.pr-num")
  SINTA_Score_Overall <- stat_profile[1] %>% html_text2()
  SINTA_Score_3Yr <- stat_profile[2] %>% html_text2()
  Affil_Score <- stat_profile[3] %>% html_text2()
  Affil_Score_3Yr <- stat_profile[4] %>% html_text2()
  Table <- sinta %>%
            html_nodes("table") %>% 
            html_table(fill = FALSE) %>% .[[1]]
  data_Scopus <- rbind(Table$Scopus[c(1,2,4)])
  data_GScholar <- rbind(Table$GScholar[c(1,2,4)])
  data_WOS <- rbind(Table$WOS[c(1,2,4)])
  vektor = c(sinta_id,nama_authors,nama_univ,nama_dept,
             SINTA_Score_Overall,SINTA_Score_3Yr,
             Affil_Score,Affil_Score_3Yr,data_Scopus, data_GScholar, data_WOS)
  df_authors = rbind(df_authors, vektor)
  print(paste("srapping page", i)) 
}
```

```{r}
colnames(df_authors) <- 
    c("SINTA_ID","Nama","Universitas","Departemen","SINTA_Score_Overall","SINTA_Score_3Yr",
     "Affil_Score","Affil_Score_3Yr","Scopus_Artikel","Scopus_Citation","Scopus_H_Index",
    "GScholar_Artikel","GScholar_Citation","GScholar_H_Index","WOS_Artikel","WOS_Citation","WOS_H_Index")

head(df_authors)
```

```{r}
View(df_authors)
```

### Export

```{r}
rio::export(df_authors, "Detail_Authors_430.csv", sep=";") 
```
