---
title: "Tugas Akhir PSD UAS"
author: "Angga Fathan Rofiqy"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: hide
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: true
pkgdown:
  as_is: true
---

Kode di `Hide` dalam *default*, untuk menampilkan kode, klik `Code` .

```{r, warning=FALSE, message = FALSE}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}
```

```{r}
path <- function(){
  gsub  ( "\\\\",  "/",  readClipboard ()  )
}
#Copy path, Panggil function di console
#Copy r path, paste ke var yang diinginkan
```

```{r}
#Export chart
export.chart <- "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/8. Pengantar Sains Data/Tugas/Tugas Akhir/Chart"
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/8. Pengantar Sains Data/Tugas/Tugas Akhir")
```

### Data Entry

```{r}
library(readxl)
data1 <- read_excel("Data PSD.xlsx")

View(data1)
str(data1)
```

```{r}
data <- data1
colnames(data) <- c('prov', 'kab/kot', 'X1', 'X2', 'X3', 'X4', 'X5', 
                    'X6', 'X7', 'X8', 'X9')
dtx <- data[,-c(1,2)]
nx  <- as.numeric(ncol(dtx))

prov <- data[,1]
kab  <- data[,2]
x1   <- dtx[,1]
x2   <- dtx[,2]
x3   <- dtx[,3]
x4   <- dtx[,4]
x5   <- dtx[,5]
x6   <- dtx[,6]
x7   <- dtx[,7]
x8   <- dtx[,8]
x9   <- dtx[,9]
```

# Explore

### 1. Statistik Deskriptif

```{r}
statdesc1 <- function(x){
      min  <- round(min(x),2)
      med  <- round(median(as.numeric(unlist(x))),2)
      mean <- round(sum(x)/nrow(x),2)
      max  <- round(max(x),2)
      var  <- round(var(x),2)
  dt <- as.data.frame(rbind(min, med, mean, max, var))
  rownames(dt) <- NULL
  return(dt)
}
```

```{r}
statdesc <- function(x){
  dt <- as.data.frame(1:5); dt <- NA
  for(i in 1:nx){
    dt <- cbind(dt, statdesc1(x[,i]))
  }
  dt <- dt[,-1]
  rownames(dt) <- c("Minimum", "Median", "Rata-rata", "Maksimum", "Ragam")
 return(dt)
}
```

```{r}
sxx <- statdesc(dtx); View(sxx)
```

### 2. Corr-Plot

```{r}
#Library visualisasi matriks korelasi
library(corrplot)
library(scales)
m <- cor(dtx) #Membuat matriks korelasi
```

```{r}
#Bikin Warna Sendiri
colors <- alpha(colorRampPalette(c("#bba58b", #Warna Bawah
                                   "#e4e4e4", #Warna Tengah
                                   "#75bfc8"))(10), #Warna Atas
                                   alpha = 0.95) #Transparan
```

```{r}
#Corrplot Elips
corrplot(m, method = 'ellipse', type='lower', order='original', col=colors)
#Corrplot Angka
corrplot(m, add=TRUE, method = 'number', type='upper', order='original',
         tl.pos = "lt", tl.col = "#78b1b0", col=colors)
```

# Clustering

```{r}
library(cluster)
library(factoextra)
library(ggplot2)
library(ggsignif)
library("tidyr")

rownames(dtx) <- data$`kab/kot`
# Scaling/Standarisasi 
df <- scale(dtx) #scale
```

### 1. Penentuan jumlah cluster optimum

```{r}
#calculate gap statistic for each number of clusters (up to 10 clusters)
gap_stat <- clusGap(df, FUN = hcut, nstart = 25, K.max = 10, B = 50)

#produce plot of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```

```{r}
## Koefisien silhoutte dan Elbow

fviz_nbclust(df, kmeans, method = "silhouette") #silhouette, k=3
fviz_nbclust(df, kmeans, method = "wss") #wss, k=1
fviz_nbclust(x = df, FUNcluster = kmeans, method = "gap_stat") #ga_stat k=1

```

```{r, error = TRUE}
library(NbClust)
library("factoextra")
nb <- NbClust(data = df, distance = "euclidean", method="kmeans")
fviz_nbclust(nb)
```

### 2. Visualization

```{r}
library(ggplot2)
library(factoextra)
library(dplyr)

# your example:
df <- scale(dtx)
set.seed(112233)
km <- kmeans(df, 4, nstart = 25)
p <- fviz_cluster(km, data = dtx, repel=TRUE,
             ellipse.type = "convex") # save to access $data

# save '$data'
dt <- p$data # this is all you need

# calculate the convex hull using chull(), for each cluster
hull_data <- dt %>%
  group_by(cluster) %>%
  slice(chull(x, y))

# plot: you can now customize this by using ggplot sintax
ggplot(dt, aes(x, y, colour = cluster)) + geom_point() +
  geom_polygon(data = hull_data, alpha = 0.2, aes(fill=cluster)) 
```

```{r}
#Banyaknya cluster dalam fungsi manual
k <- 4
for(i in 1:k){
  cat("Cluster",i,":", length(which(dt$cluster==i)),"\n")
}
```

```{r}
#liat hasil clustering
n <- ncol(data)
kelas <- cbind(data[,1:2],dt$cluster,data[,3:n])
colnames(kelas)[3] <- "Cluster"
View(kelas)
```

```{r}
#Export kelas
repo  <- gsub  ( "\\\\",  "/",  readClipboard ()  ); repo
```

```{r}
library("writexl")
write_xlsx(kelas, "C:/Users/Fathan/Documents/[Kuliah]/[semester 4]/07 AED/Tugas/Clustering/Output data/Hasil_Cluster.xlsx")
```

```{r}
#FUNGSI K-MEANS CENTROID
mykmeans <- function (data, k, centers = NULL, stop_crit = 10e-3, seed = 1001)
{

  # Initializations
  set.seed(seed)
  # Assigning the initial centroids. Random value will be used
  # if no values were specified
  if(is.null(centers)) centers = sample.int(nrow(data), k)
  centroid <- data[centers, ]
  # Keep a history of the centroid values for visualization purpose
  cen_hist = data.frame(centroid)
  # Randomly assign clusters to each observations
  cluster <- c(sample.int(k, nrow(data), replace = TRUE))
  # Keep a histpry of the data frame that includes assigned clusters
  # for visualization purpose
  data_hist <- data.frame(data,cluster)
  # Within group Sum of squares
  withinss = c()
  # size of each cluster
  size = c()
  # Does it converge?
  conver <- F
  # distance between old and updated centroids
  # Set it as arbitarily large
  dist_crit = 10e5
  # Number of iteration
  iter = 1
  
  while (conver == FALSE)
  {
    old_centroid = centroid
    
    # assign to cluster that has the closest centroid to a specific data point
    for (i in 1 : nrow(data))
    {
      dist = apply(centroid, 1, function(x) sum((x - data[i,])^2))
      cluster[i] = which.min(dist)
    }
    
    # Update the centroid mean
    for (j in 1 : k)
    {
      centroid[j, ] = apply(data[cluster == j, ], 2, mean)
    }
    
    ## Keep the history of the centroid and data + cluster
    cen_hist = rbind(cen_hist, data.frame(centroid))
    data_hist = rbind(data_hist, data.frame(data,cluster))
    
    # Is the stopping criteria met?
    dist_crit = mean(as.numeric(unlist(old_centroid - centroid)^2), na.rm = TRUE)
    if (dist_crit <= stop_crit) conver = TRUE
    
    # Update iteration
    iter = iter + 1
  }
  
  #### Sum of squares calculations#####
  for (m in 1 : k)
  {
    withinss[m] = sum((apply(data[cluster == m, ],1, 
                             function(x) x - apply(data[cluster == m, ],2,mean)))^2)
    size [m] = sum(cluster == m)
  }
  
  totss = sum(apply(data, 1, function(x) sum((x - apply(data,2,mean))^2)))
  tot.withinss = sum(withinss)
  
  return(list(data = data.frame(data,cluster),
              cluster = cluster,
              centroid = centroid,
              totss = totss,
              withinss = withinss,
              tot.withinss = tot.withinss,
              betweenss = totss - tot.withinss,
              size = size,
              cen_hist = cen_hist,
              data_hist = data_hist,
              iterations = iter))
}
```

```{r}
#INPUT DATA
k = 4 #n cluster
res=mykmeans(dt[c(2,3)],k=k)
res$centroid$cluster=1:k
res$data$isCentroid=F
res$centroid$isCentroid=T
data_plot2=rbind(res$centroid,res$data)

ggplot(data_plot2,aes(x=x,y=y,color=as.factor(cluster),
                           size=isCentroid,alpha=isCentroid)) +
  geom_point() + theme_light()
```
