---
title: "Tugas Akhir PSD UAS"
author: "Angga Fathan Rofiqy"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: hide
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: true
pkgdown:
  as_is: true
---

```{r, warning=FALSE, message = FALSE}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}

```

### Data Entry

```{r, warning=FALSE, message = FALSE}
install_load('rio')
raw.data1 <- import("https://raw.githubusercontent.com/Zen-Rofiqy/STA1381-PSD/main/Tugas/Tugas%20Akhir/Data%20PSD.csv")

raw.data2 <- import("https://raw.githubusercontent.com/Zen-Rofiqy/STA1381-PSD/main/Tugas/Tugas%20Akhir/Data%20PSD_Perc.csv")

raw.data3 <- import("https://raw.githubusercontent.com/Zen-Rofiqy/STA1381-PSD/main/Tugas/Tugas%20Akhir/Data%20PSD_Desa.csv")
```

## Library

```{r message=FALSE, warning=FALSE}
install_load("ppclust", "factoextra", "dplyr", "cluster", "fclust", "psych", 
             "FactoMineR", "ggplot2", "fmsb")
```

## GMM

```{r}
library("mclust")
mod1 = Mclust(dtx)
mod1$BIC
```

### Jumlah Cluster

```{r dpi=300,  fig.height = 5, fig.width = 9, fig.align = "center", warning=FALSE, message = FALSE}
plot(mod1, what = 'BIC')
```

```{r}
mod1b = Mclust(dtx, G = 5, modelNames = c("VEI"))
summary(mod1b, parameters = TRUE)
```

```{r}
library(dplyr)

# Menghitung frekuensi observasi di setiap kluster
cluster_frequencies <- table(mod1b$classification)

# Mengurutkan kluster berdasarkan frekuensinya
sorted_clusters <- names(sort(cluster_frequencies, decreasing = TRUE))

# Membuat urutan kluster yang diinginkan (1, 2, 3, 4, 5)
new_order <- 1:length(sorted_clusters)

# Menukar isi kluster dengan urutan yang dihasilkan
mod1b$classification <- recode(mod1b$classification, !!!setNames(as.character(new_order), sorted_clusters))

table(mod1b$classification)
```

### Plot Cluster

```{r}
library(factoextra)
fviz_cluster(mod1b, data = dtx, repel = TRUE, labelsize =8)
```

### Profil

```{r}
data.clust1 <- cbind(dtx, Cluster = mod1b[["classification"]])

# Calculate the mean of each variable for each cluster
cluster_profiles1 <- aggregate(. ~ Cluster, data.clust1, mean)

# Print the cluster profiles
print(cluster_profiles1)
```

```{r}
# Convert the data to long format for plotting
cluster_profiles_long1 <- tidyr::pivot_longer(cluster_profiles1, -Cluster, 
                                             names_to = "Variable", values_to = "Value")

# Create the bar plot
ggplot(cluster_profiles_long1, aes(x = Cluster, y = Value, fill = Variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Cluster", y = "Mean Value", fill = "Variable") +
  theme_minimal() +
  ggtitle("Cluster Profiles")
```

```{r dpi=300,  fig.height = 12, fig.width = 12, fig.align = "center", warning=FALSE, message = FALSE}
library(ggiraphExtra)

data.akhir1 <- cbind(raw.data2[-35,], Cluster =  mod1b[["classification"]]) %>% 
  relocate(Cluster, .before = 2)

# Radar Plot
ggRadar(
  data = data.akhir1,
  mapping = aes(colours = Cluster)
) + 
theme_light() +
theme(
  text = element_text(size = 10),  # Mengubah ukuran font global
  title = element_text(size = 12),  # Mengubah ukuran font judul
  axis.text = element_text(size = 10),  # Mengubah ukuran font label sumbu
  legend.text = element_text(size = 8)  # Mengubah ukuran font legenda
)
```

### Map

```{r message=FALSE, warning=FALSE}
install_load("spdep","rgdal")
indo <- st_read(dsn= paste0(wd,"/SHP Indonesia/prov.shp"), 
                quiet = TRUE)
```

```{r}
data.map <- cbind(data.clust1, KODE=raw.data3$KODE[-35])
  
data.indo <- indo %>%
  inner_join(data.map, by = c("KODE" = "KODE"))
```

```{r dpi=300,  fig.height = 9, fig.width = 16, fig.align = "center", warning=FALSE, message = FALSE}
ggplot() +  
  geom_sf(data=data.indo, aes(fill=factor(`Cluster`))) +
  scale_fill_manual(values=c("1" = "indianred", "2" = "lightgreen", "3" = "dodgerblue",
                             "4"="cyan3", "5"="purple3"), 
                    name = "Keterangan") +
  labs(title = "Cluster Bencana Alam \n pada Provinsi Indonesia 2021",
       x = "Longitude",
       y = "Latitude") +
  theme_minimal() +
  theme(legend.text = element_text(size=10),
        legend.title = element_text(size=10, face="bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size=12, face="bold", hjust = 0.5)) +
  scale_x_continuous(labels = function(x) paste0(x, "°")) +
  scale_y_continuous(labels = function(y) paste0(y, "°"))
```
