---
title: "Prep"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output: html_document
---

## Preparing

```{r, warning=FALSE, message = FALSE}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}
```

```{r}
path <- function(){
  gsub  ( "\\\\",  "/",  readClipboard ()  )
}
#Copy path, Panggil function di console
#Copy r path, paste ke var yang diinginkan
```

```{r}
#Export chart
export.chart <- "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/8. Pengantar Sains Data/Tugas/Tugas Akhir/Chart"
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/8. Pengantar Sains Data/Tugas/Tugas Akhir")
```

## Data

```{r}
library(readxl)
data1 <- read_excel("Data PSD.xlsx", sheet = 2)
data2 <- read_excel("Data PSD.xlsx", sheet = 3)
data3 <- read_excel("Data PSD.xlsx", sheet = 4)
```

## Export

```{r}
write.csv(data1, "Data PSD.csv", row.names=FALSE)
write.csv(data2, "Data PSD_Perc.csv", row.names=FALSE)
write.csv(data3, "Data PSD_Desa.csv", row.names=FALSE)
```
